### PR TITLE
Updates `.bump2version` config when updating `CHANGELOG`

### LINKED ISSUE #89: build job fails for every version bump commit in main branch
For every new version the main branch runs our test pipeline. However, the build tasks fails all the [time](https://github.com/MDAnalysis/mdacli/runs/4869599287?check_suite_focus=true). The reason is that there is 
no `new_version` statement in the CHANGELOG.rst since exactly we change the version to the 'new' one (see for example https://github.com/MDAnalysis/mdacli/commit/33eb1df2b1134bc087d8546705ea17d35b4aed9e). It is probably useful to disable the build test for pushes to main branch for example by removing the two lines

https://github.com/MDAnalysis/mdacli/blob/33eb1df2b1134bc087d8546705ea17d35b4aed9e/.github/workflows/build.yml#L4-L5

What do you think @joaomcteixeira ?

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Closes #89 (should)

### CODE REVIEW

**Review by PicoCentauri — APPROVED** [review]

**Comment by joaomcteixeira** [comment]
Hmm... I don't know if I like that behaviour. Previously, that was not possible and I liked that.

**Comment by PicoCentauri** [comment]
I am also not sure. One idea would be to not run the test on the main branch…

**Comment by joaomcteixeira** [comment]
Some time ago, I had a script that confirmed if the CHANGELOG was updated. Then, I changed the `.bump2version.cfg` to a behaviour similar to what we had here now; where it would fail if the changelog was not updated. But actually, I was having problems in this repo and in other repos with this last configuration. So, I think I will revert to the script in `devtools`.

**Comment by joaomcteixeira** [comment]
Done @PicoCentauri . this should solve the issue

**Comment by PicoCentauri** [comment]
I like!

**Pull request merged**
